"""
questions_seed.py  —  NetLab Question Bank
All sample questions are defined here.
Each entry: (category, question_text, options_list_or_None, correct_answer, points, time_seconds)
Import and use `SEED_QUESTIONS` in app.py.
"""

SEED_QUESTIONS = [
    # ── TOPOLOGY (8 questions) ────────────────────────────────────────────
    ("topology",
     "In Cisco Packet Tracer, you connect all PCs to one central switch. What topology is this?",
     ["Bus", "Ring", "Star", "Mesh"],
     "Star", 2, 45),
    ("topology",
     "In a bus topology, what happens when the main backbone cable breaks?",
     ["Only one PC loses connection", "The network splits in two",
      "All devices lose communication", "Nothing changes"],
     "All devices lose communication", 2, 45),
    ("topology",
     "In Packet Tracer, every router is connected directly to every other router. What topology is this?",
     ["Star", "Bus", "Full Mesh", "Ring"],
     "Full Mesh", 2, 45),
    ("topology",
     "Which topology is the easiest to add a new PC to in Packet Tracer without disrupting other devices?",
     ["Bus", "Ring", "Mesh", "Star"],
     "Star", 2, 45),
    ("topology",
     "In a ring topology in Packet Tracer, data travels in which direction?",
     ["Both directions simultaneously", "Only left to right",
      "One direction around the ring", "Randomly"],
     "One direction around the ring", 2, 45),
    ("topology",
     "You have 4 PCs connected to a hub in Packet Tracer. What topology does this represent?",
     ["Mesh", "Bus", "Ring", "Star"],
     "Star", 2, 45),
    ("topology",
     "Which topology requires the MOST cables when connecting 5 devices together directly (no switch)?",
     ["Star", "Bus", "Ring", "Full Mesh"],
     "Full Mesh", 2, 45),
    ("topology",
     "A school lab uses one long cable with all PCs tapped into it. What topology is this?",
     ["Star", "Ring", "Bus", "Tree"],
     "Bus", 2, 45),

    # ── IPv4 ADDRESSING (8 questions) ─────────────────────────────────────
    ("ip_addr",
     "In Packet Tracer, PC0 is 192.168.1.10/24 and PC1 is 192.168.1.20/24. Can they ping each other without a router?",
     ["No – different networks", "Yes – same network",
      "No – wrong mask", "Yes – only with NAT"],
     "Yes – same network", 2, 45),
    ("ip_addr",
     "What subnet mask do you enter in Packet Tracer for a /24 network?",
     ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.128"],
     "255.255.255.0", 2, 45),
    ("ip_addr",
     "PC0 has IP 192.168.1.1/24. The router LAN interface is 192.168.1.254. What default gateway do you enter on PC0?",
     ["192.168.1.1", "192.168.1.255", "192.168.1.254", "192.168.0.1"],
     "192.168.1.254", 2, 45),
    ("ip_addr",
     "In Packet Tracer, PC0 is 10.0.0.1/8 and PC1 is 10.0.0.2/8. What is their shared network address?",
     ["10.0.0.0", "10.255.255.255", "10.0.0.1", "0.0.0.0"],
     "10.0.0.0", 2, 45),
    ("ip_addr",
     "You ping 127.0.0.1 from a PC in Packet Tracer. What does a successful reply confirm?",
     ["The gateway is reachable", "The DNS is working",
      "The PC network stack is working", "Another PC replied"],
     "The PC network stack is working", 2, 45),
    ("ip_addr",
     "In Packet Tracer, two PCs are on different subnets. What device must you add so they can communicate?",
     ["Hub", "Switch", "Router", "Repeater"],
     "Router", 2, 45),
    ("ip_addr",
     "Which IP address class does 172.16.0.0 belong to?",
     ["Class A", "Class B", "Class C", "Class D"],
     "Class B", 2, 45),
    ("ip_addr",
     "In Packet Tracer, which address is used to send data to ALL hosts on the 192.168.1.0/24 network?",
     ["192.168.1.0", "192.168.1.1", "192.168.1.255", "255.255.255.255"],
     "192.168.1.255", 2, 45),

    # ── IP CALCULATION (4 questions, text answers) ─────────────────────────
    ("ip_calc",
     "PC in Packet Tracer has IP 192.168.1.50 with mask 255.255.255.0. What is the broadcast address of its network?",
     None, "192.168.1.255", 3, 90),
    ("ip_calc",
     "You are given network 192.168.10.0/24 in Packet Tracer. How many usable host IP addresses can you assign to PCs?",
     None, "254", 3, 90),
    ("ip_calc",
     "A network is 10.0.0.0/8. How many usable host addresses does it have?",
     None, "16777214", 3, 90),
    ("ip_calc",
     "Host IP is 192.168.5.130/25. What is the network address of this subnet?",
     None, "192.168.5.128", 3, 90),

    # ── CABLES & CONNECTIONS (8 questions) ───────────────────────────────
    ("cables",
     "In Packet Tracer, which cable type do you use to connect a PC to a switch?",
     ["Crossover cable", "Fiber optic", "Straight-through copper", "Serial cable"],
     "Straight-through copper", 2, 45),
    ("cables",
     "In Packet Tracer, you connect Switch0 directly to Switch1. Which cable type should you choose?",
     ["Straight-through", "Crossover", "Rollover", "Fiber optic"],
     "Crossover", 2, 45),
    ("cables",
     "In Packet Tracer, which cable type connects a router serial interface to another router serial interface (WAN link)?",
     ["Straight-through", "Crossover", "Serial DCE/DTE cable", "Fiber optic"],
     "Serial DCE/DTE cable", 2, 45),
    ("cables",
     "When Packet Tracer shows a RED dot on a cable connection, what does it mean?",
     ["Link is fast", "Link is active", "Interface is down or wrong cable used", "Cable is fiber optic"],
     "Interface is down or wrong cable used", 2, 45),
    ("cables",
     "A GREEN dot on both ends of a Packet Tracer cable connection means:",
     ["IP conflict on the link", "Link is active and working",
      "Cable is a crossover type", "Port is administratively shut down"],
     "Link is active and working", 2, 45),
    ("cables",
     "In Packet Tracer, which cable connects a PC console port to a router for initial CLI configuration?",
     ["Straight-through", "Crossover", "Rollover (Console) cable", "Serial cable"],
     "Rollover (Console) cable", 2, 45),
    ("cables",
     "Which physical connector is crimped on both ends of a standard UTP Ethernet cable?",
     ["RJ-11", "BNC", "RJ-45", "LC"],
     "RJ-45", 2, 45),
    ("cables",
     "In Packet Tracer, you connect PC0 directly to PC1 with no switch in between. Which cable must you use?",
     ["Straight-through", "Serial", "Crossover", "Fiber"],
     "Crossover", 2, 45),

    # ── DATA FLOW (6 questions) ───────────────────────────────────────────
    ("data_flow",
     "In Packet Tracer Simulation Mode, you send a ping from PC0 to a switch. What is the PDU type the switch processes?",
     ["Segment", "Packet", "Ethernet Frame", "Bit stream"],
     "Ethernet Frame", 2, 45),
    ("data_flow",
     "In Packet Tracer, a switch decides which port to forward a frame to based on which address?",
     ["IP address", "MAC address", "Port number", "Hostname"],
     "MAC address", 2, 45),
    ("data_flow",
     "PC0 (192.168.1.1) pings PC1 (192.168.2.1) – a different subnet. Which device must the packet pass through in Packet Tracer?",
     ["A hub", "A switch", "A router", "A repeater"],
     "A router", 2, 45),
    ("data_flow",
     "PC0 pings a device it has never contacted before. What protocol does it broadcast first to find the destination MAC address?",
     ["ICMP", "DNS", "ARP", "DHCP"],
     "ARP", 2, 45),
    ("data_flow",
     "In Packet Tracer Simulation Mode, which colour envelope represents an ICMP (ping) PDU?",
     ["Green", "Blue", "Yellow", "Red"],
     "Yellow", 2, 45),
    ("data_flow",
     "A hub in Packet Tracer receives a frame on Port 1. What does it do with the frame?",
     ["Sends it only to the correct MAC", "Drops it with an error",
      "Floods it out ALL other ports", "Stores it in a buffer"],
     "Floods it out ALL other ports", 2, 45),

    # ── HARDWARE DEVICES (5 questions) ────────────────────────────────────
    ("hardware",
     "In Packet Tracer, which device connects multiple PCs in a LAN and forwards frames only to the correct port using a MAC table?",
     ["Hub", "Repeater", "Switch", "Modem"],
     "Switch", 2, 45),
    ("hardware",
     "In Packet Tracer, you need to link two networks: 192.168.1.0/24 and 192.168.2.0/24. Which device do you drag onto the canvas?",
     ["Switch", "Hub", "Access Point", "Router"],
     "Router", 2, 45),
    ("hardware",
     "In Packet Tracer, which device broadcasts every received signal out of ALL its ports with no MAC-address intelligence?",
     ["Switch", "Router", "Hub", "Firewall"],
     "Hub", 2, 45),
    ("hardware",
     "In Packet Tracer, which device allows wireless laptops to join a wired LAN?",
     ["Hub", "Switch", "Wireless Access Point", "Repeater"],
     "Wireless Access Point", 2, 45),
    ("hardware",
     "In Packet Tracer, what is the name of the router interface that faces the internal LAN (e.g. Fa0/0)?",
     ["WAN interface", "Serial interface", "LAN / FastEthernet interface", "Console port"],
     "LAN / FastEthernet interface", 2, 45),

    # ── TRANSMISSION MEDIUM (5 questions) ─────────────────────────────────
    ("medium",
     "Which transmission medium carries data as pulses of light and is immune to electromagnetic interference (EMI)?",
     ["UTP copper cable", "Coaxial cable", "Fiber optic cable", "Radio waves"],
     "Fiber optic cable", 2, 45),
    ("medium",
     "In Packet Tracer, which medium is shown as a zigzag wireless link between a laptop and an access point?",
     ["Copper UTP", "Fiber optic", "Coaxial", "Radio waves (Wi-Fi)"],
     "Radio waves (Wi-Fi)", 2, 45),
    ("medium",
     "Which cable medium is most commonly used in Packet Tracer LAN labs to connect PCs and switches?",
     ["Coaxial cable", "Fiber optic", "UTP copper (Cat5e/Cat6)", "Serial cable"],
     "UTP copper (Cat5e/Cat6)", 2, 45),
    ("medium",
     "Which transmission medium is MOST susceptible to interference from nearby electrical equipment?",
     ["Fiber optic", "UTP copper cable", "Coaxial cable", "Satellite"],
     "UTP copper cable", 2, 45),
    ("medium",
     "In Packet Tracer, which cable type is used on WAN serial links between routers, representing a leased-line medium?",
     ["UTP straight-through", "Fiber LC", "Serial (V.35) cable", "Rollover cable"],
     "Serial (V.35) cable", 2, 45),

    # ── NEW TRICKY QUESTIONS (7 questions, 30 sec) ────────────────────────

    # ip_addr — IP conflict
    ("ip_addr",
     "PC0 and PC1 are both configured with IP 192.168.1.1 on the same switch. PC2 (192.168.1.3) pings 192.168.1.1. What most likely happens?",
     ["Both PC0 and PC1 reply successfully",
      "PC2 gets no reply — the switch blocks duplicate IPs",
      "PC2 gets unpredictable results — IP conflict causes random or failed replies",
      "The switch automatically assigns a new IP to one of them"],
     "PC2 gets unpredictable results — IP conflict causes random or failed replies", 2, 30),

    # ip_addr — loopback
    ("ip_addr",
     "A student pings 127.0.0.1 on PC0 and gets a reply. He unplugs the network cable and pings again. What happens?",
     ["The ping fails — no cable means no network",
      "The ping fails — the IP becomes invalid without a cable",
      "The ping times out after 30 seconds",
      "The ping still succeeds — 127.0.0.1 never leaves the PC"],
     "The ping still succeeds — 127.0.0.1 never leaves the PC", 2, 30),

    # ip_calc — binary to decimal (192.168.1.10)
    ("ip_calc",
     "In Packet Tracer, a PC IP in binary is: 11000000.10101000.00000001.00001010\nWhat is the decimal IP? (e.g. 10.0.0.1)",
     None, "192.168.1.10", 3, 30),

    # ip_calc — binary to decimal (172.16.5.20)
    ("ip_calc",
     "In Packet Tracer, a PC IP in binary is: 10101100.00010000.00000101.00010100\nWhat is the decimal IP? (e.g. 10.0.0.1)",
     None, "172.16.5.20", 3, 30),

    # hardware — cable count Q1 (1 router, 2 switches, 6 PCs)
    ("hardware",
     "In Packet Tracer: 1 router, 2 switches, 6 PCs (3 PCs per switch), both switches connect to the router. How many total cable connections? (Type only the number)",
     None, "9", 3, 30),

    # hardware — cable count Q2 (3 routers full mesh, 3 switches, 4 PCs each)
    ("hardware",
     "In Packet Tracer: 3 routers in full mesh, each router connects to 1 switch, each switch has 4 PCs. How many total cable connections? (Type only the number)",
     None, "18", 3, 30),

    # hardware — cable count Q3 (2 routers, asymmetric switches)
    ("hardware",
     "In Packet Tracer: 2 routers connected to each other, Router A has 1 switch with 4 PCs, Router B has 2 switches each with 3 PCs. How many total cable connections? (Type only the number)",
     None, "13", 3, 30),
]